Pesquisar front end #9
ES2-UFPI/AnimL pull request #34
Opened 2021-11-02 20:16 UTC by gabrielscn

2021-11-03 00:00 UTC, NondasNF approved these changes
O codigo esta ok, só vale lembrar que não é uma boa prática utilizar nomes de cores ao invez do código hexadecimal ou rgb, fora isso esta bom!

2021-11-03 00:31 UTC, thodoroki approved these changes
ok

2021-11-03 01:43 UTC, MirandaFernando commented
Acredito que algumas coisas podem ser melhorada, vou te mandar uma lista no slack.

2021-11-03 12:13 UTC, MirandaFernando requested changes
.

2021-11-03 17:25 UTC, thodoroki commented
> ok

Pode ser feita algumas melhoras a respeito da estilização.

2021-11-08 03:24 UTC, thodoroki approved these changes

2021-11-08 03:25 UTC, thodoroki commented
A lista que aparecem os nomes sugeridos de pesquisa tá meio feinha mas tudo certo.

2021-11-08 16:10 UTC, merged