Buscar info anime
ES2-UFPI/AnimL pull request #39
Opened 2021-11-03 18:46 UTC by MirandaFernando

Criando pagina com informações de um anime especifico.

2021-11-03 18:50 UTC, NondasNF approved these changes
Um bom inicio para uma escalabilidade maior ainda dentro das possiveis expasões dessa issue

2021-11-03 18:50 UTC, gabrielscn requested changes
Acho que as alterações feitas poderiam ser mais profundamente elaboradas portanto acho que não deveria ser feito o merge desta pr.

2021-11-05 21:42 UTC, gabrielscn approved these changes

2021-11-05 21:47 UTC, thodoroki approved these changes
ok

2021-11-06 04:21 UTC, merged